Small volfrac
AMReX-Codes/amrex pull request #1228
Opened 2020-08-04 18:11 UTC by drangara

## Summary

## Additional background

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

2020-08-06 15:43 UTC, drangara commented
When `extend_domain_face` is set to true we do the following: If we set a cell that lies on one of the 6 faces of the domain as `covered` because its volfrac is less than the small_volfrac , we are forcing the corresponding ghost cells on that face to also be `covered`.

2020-08-06 19:49 UTC, WeiqunZhang requested changes

2020-08-06 19:49 UTC, WeiqunZhang commented on Src/EB/AMReX_EB2_3D_C.cpp
> +                        set_covered(ii,j,k,cell,vfrac,vcent,barea,bcent,bnorm);
The problem is there is a race condition on GPU.  There is another thread that has been assigned to work on cell (ii,j,k).  If both threads are trying to write the data of cell(ii,j,k), it's undefined which thread will win.  I think you will have to fix the extended face after this kernel.  You can launch a kernel on `bxg1`.  In the kernel, you test on if this cell in extended region.  If yes, you test on its original source to see if that has been covered.  If that is covered, you can then set this extended cell to covered.  Also note that you need to make sure periodic boundary has been taken into account.  We do not extend at periodic boundaries.

2020-08-08 18:48 UTC, WeiqunZhang commented on Src/EB/AMReX_EB2_2D_C.cpp
> +    if(extend_domain_face) {
We don't need to launch a kernel if the box is not at the domain boundary.  Moreever, `Geometry` cannot be used on device.  How about something like this here?
```
Box gdomain = geom.Domain();
for (int idim = 0; idim < AMREX_SPACEDIM; ++idim) {
    if (geom.isPeriodic(idim)) {
        gdomain.setSmall(idim,std::min(gdomain.smallEnd(idim),bxg1.smallEnd(idim)));
        gdomain.setBig(idim,std::max(gdomain.bigEnd(idim),bxg1.bigEnd(idim)));
    }
}
if (not gdomain.contains(bxg1)) {
    AMREX_HOST_DEVICE_FOR_3D ( bxg1, i, j, k,
   {
       // No need to use geom
       // use gdomain
   });
}
```

2020-08-09 20:26 UTC, WeiqunZhang approved these changes

2020-08-09 20:34 UTC, merged