Add SENSEI adaptor and bridge for amrMesh+Particles
AMReX-Codes/amrex pull request #2285
Opened 2021-08-26 20:16 UTC by c-wetterer-nelson

## Summary
This PR adds a new composite data adaptor which enables processing AmrMesh data alongside ParticleContainer data. 

Currently tested working in WarpX with the [3D Beam-driven electron acceleration](https://warpx.readthedocs.io/en/latest/usage/examples.html) using the WarpX version in https://github.com/ECP-WarpX/WarpX/pull/2243.

This PR also reworks how the ParticleDataAdapter loops over particle data. 

## Additional background

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2021-08-26 20:17 UTC, c-wetterer-nelson commented
@ax3l WarpX PR inbound.

2021-08-26 20:18 UTC, c-wetterer-nelson commented
@burlen Here's that AmrMesh + particle data adaptor! I've been working to make sure it works in WarpX, but I've been unsuccessful getting it working in our em PIC example you put together in amrex-tutorials. Still struggling with valid particles there.

2021-08-27 19:05 UTC, burlen requested changes
WarpX is just one use case of many possible. Had you tested this with the neighbor particle example as well? While it is great that it's working with WarpX I think we need to get it working with the other demos before merging. @c-wetterer-nelson Let's make some time for a hacking session to debug the issues you're experiencing in the other codes.

I also would like us to not use virtual method calls to set the individual values of arrays when pointers (or non-virtual API) could be used.

2021-08-27 19:05 UTC, burlen commented on Src/Extern/SENSEI/AMReX_ParticleDataAdaptorI.H
> +          idArray->SetTuple1(ptId, part.id());
This changes from dereferencing a pointer to calling a virtual method to pass a single value. This adds unnecessary overhead and I had put the effort to refactor the code from the virtual methods to using pointers. Please don't use the virtual API when a pointer can be used instead.

2021-08-27 19:05 UTC, burlen commented on Src/Extern/SENSEI/AMReX_ParticleDataAdaptorI.H
> +          cpuArray->SetTuple1(ptId, part.cpu());
Same request. Please use pointer to the data rather than virtual method call to set values on the vtk array

2021-08-27 19:05 UTC, burlen commented on Src/Extern/SENSEI/AMReX_ParticleDataAdaptorI.H
> +          data->SetTuple1(ptId, intData[i]);
same request, avoid virtual methods when passing array elements.

2021-08-27 19:05 UTC, burlen commented on Src/Extern/SENSEI/AMReX_ParticleDataAdaptorI.H
> +          points->SetPoint(ptId, part.pos(0), 0.0, 0.0);
this changes from dereferencing a pointer to a virtual method call to pass point values. Please don't use virtual methods to set the values of an array.

2021-08-27 19:31 UTC, c-wetterer-nelson commented
Hi @burlen, thanks for the review! I appreciate your concern with the virtual function calls. When I was trying to get this thing working in WarpX, I was having all sort of strange crashes and memory issues, so I went through and refactored the whole thing and the result was a working adaptor in warpx! However, that refactor  included the above noted virtual function calls _and_ redoing how we iterate over particles to line up with the AMReX tutorials. I have a hunch we can keep the updated iteration and roll back to your array assignment organization. better yet, maybe we take the opportunity to make this all zero copy?

2021-08-27 22:48 UTC, burlen commented
> Hi @burlen, thanks for the review! I appreciate your concern with the virtual function calls. When I was trying to get this thing working in WarpX, I was having all sort of strange crashes and memory issues, so I went through and refactored the whole thing and the result was a working adaptor in warpx! However, that refactor included the above noted virtual function calls _and_ redoing how we iterate over particles to line up with the AMReX tutorials. I have a hunch we can keep the updated iteration and roll back to your array assignment organization. better yet, maybe we take the opportunity to make this all zero copy?

Glad you got it working, SetTuple can be replaced with pointer manipulations(after all it's what goes on inside the SetTuple calls), your other changes are what made the difference.

zero copy won't be possible until we modify VTK to handle AOS case. VTK is missing stride that tells the offset between array elements. VTK's AOS arrays currently assume a stride of NumberOfTuples which works for VTK's representation of  vectors but does not work in general for C structs. This is one of the motivations for forking VTK.

2021-08-28 06:12 UTC, c-wetterer-nelson commented
Update to the particle adaptor. This addresses the virtual function call concerns above and keeps the updated iterator layout. Successfully tested in the Neighborlist demo! 

Tests:
- WarpX 3D example problem: Working
- amrex-tutorials/SENSEI/Advection_AmrLevel: Working
- amrex-tutorials/SENSEI/Particles/Neighborlist: Working
- amrex-tutorials/SENSEI/Particles/ElectromagneticPIC: still on the fritz (pretty sure it's not the adaptor's fault)

2021-08-30 17:05 UTC, burlen commented
@c-wetterer-nelson this is awersome! thanks for testing with the various tutorials and avoiding VTK data array virtaul API. We have yet to get the EM PIC tutorial working so if you agree we can leave that for future work.

I don't see how to change my review so I'll leave this in a comment.

2021-08-30 18:36 UTC, c-wetterer-nelson commented
thanks @burlen! I think you can start a new review and the new review will replace the old one. 

I agree on the EMPIC future work.

2021-09-01 22:08 UTC, burlen approved these changes
this looks good to me.

2021-09-01 22:46 UTC, atmyers approved these changes

2021-09-01 22:47 UTC, merged