Docs: MLMG solver convergence criteria
AMReX-Codes/amrex pull request #2413
Opened 2021-10-18 16:56 UTC by roelof-groenewald

## Summary

Expanded the documentation with regards to convergence criteria for the MLMG solver

## Additional background

This is in response to @RemiLehe's request for expanded documentation for [WarpX PR #2410](https://github.com/ECP-WarpX/WarpX/pull/2410). I figured it is better to keep the explanation of the different convergence parameters in the AMReX documentation and just add a link to it in the WarpX documentation.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2021-10-18 23:12 UTC, WeiqunZhang requested changes

2021-10-18 23:12 UTC, WeiqunZhang commented on Docs/sphinx_documentation/source/LinearSolvers.rst
> +error tolerance is hard-coded to be at least :math:`10^{-16}`.
The absolute error tolerance is *not* hard-coded to be at lease 1e-16.  The relative tolerance is.

2021-10-18 23:12 UTC, WeiqunZhang commented on Docs/sphinx_documentation/source/LinearSolvers.rst
> +is the max-norm of the solution, :math:`f`, if the flag :cpp:`always_use_bnorm`
The code is
```
    if (always_use_bnorm || rhsnorm0 >= resnorm0) {
        norm_name = "bnorm";
        max_norm = rhsnorm0;
    } else {
        norm_name = "resid0";
        max_norm = resnorm0;
    }
```
Assuming the linear system is `A x = b`, `rhsnorm0` is the max-norm of `b` and `resnorm0` is the max-norm of the residual (i.e., `b - Ax`).

2021-10-18 23:49 UTC, roelof-groenewald commented on Docs/sphinx_documentation/source/LinearSolvers.rst
> +error tolerance is hard-coded to be at least :math:`10^{-16}`.
Whoops. Thanks for catching!

2021-10-18 23:52 UTC, roelof-groenewald commented on Docs/sphinx_documentation/source/LinearSolvers.rst
> +is the max-norm of the solution, :math:`f`, if the flag :cpp:`always_use_bnorm`
Would you like me to add the code snippet to the documentation instead of the written out explanation?

2021-10-19 00:04 UTC, WeiqunZhang commented on Docs/sphinx_documentation/source/LinearSolvers.rst
> +is the max-norm of the solution, :math:`f`, if the flag :cpp:`always_use_bnorm`
I am thinking of using words and `A x = b` so that it's clear what RHS and residual mean.

2021-10-19 00:27 UTC, WeiqunZhang requested changes

2021-10-19 00:27 UTC, WeiqunZhang commented on Docs/sphinx_documentation/source/LinearSolvers.rst
> +:cpp:`always_use_bnorm` is set to True or if the solution max-norm is greater
I don't think we should call `b` solution.  The solution is `x` and rhs is `b`.

2021-10-19 16:23 UTC, WeiqunZhang approved these changes

2021-10-19 16:23 UTC, merged