Support implicit function class defined on host when using device memory explicitly.
AMReX-Codes/amrex pull request #2563
Opened 2022-01-06 04:40 UTC by hengjiew

## Summary 
AMReX needs to use managed memory if the user-defined implicit function (IF) class's member functions are only callable by the host. This PR allows users to use IF classes defined on the host with device memory.

## Additional background

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2022-01-06 17:50 UTC, WeiqunZhang requested changes
It might be better to use the async version of the dtoh and htod memcpy and add an explicit stream sync at the end of the scope for the temporary fabs in the pinned memory.

2022-01-06 17:50 UTC, WeiqunZhang commented on Src/EB/AMReX_EB2_GeometryShop.H
> +        const Box& bx = levelset.box();
Minor comment.  We can move the line above inside the if block.

2022-01-06 17:50 UTC, WeiqunZhang commented on Src/EB/AMReX_EB2_GeometryShop.H
> +            if (!The_Arena()->isManaged()) {
```suggestion
            if (!The_Arena()->isHostAccessible()) {
```

2022-01-06 17:50 UTC, WeiqunZhang commented on Src/EB/AMReX_EB2_GeometryShop.H
>              const Box bx{inter};
We can move this Box inside the if block.

2022-01-06 17:50 UTC, WeiqunZhang commented on Src/EB/AMReX_EB2_GeometryShop.H
> +                const auto& h_type  = h_type_fab.array();
```suggestion
                const auto& h_type  = h_type_fab.const_array();
```

2022-01-07 17:29 UTC, hengjiew commented
> It might be better to use the async version of the dtoh and htod memcpy and add an explicit stream sync at the end of the scope for the temporary fabs in the pinned memory.

Hello @WeiqunZhang, do you mean sth like this?
```
dtoh_memcpy_async(h_levelset.dataPtr(), levelset.dataPtr(), ...);
fillFab_cpu(h_levelset, ...);
htod_memcpy_async(d_levelset.dataPtr(), h_levelset.dataPtr(), ...);
streamSynchronize();
```
I am not sure if this will work because the host function `fillFab_cpu` and the copy to pinned memory have data dependence (h_levelset) and need to be executed in serial.

2022-01-07 23:08 UTC, WeiqunZhang commented
Yes, you are right that we need an extra `streamSynchronize` in `getIntercept` if we use the async version of memcpy.  However, for the code shown above, I don't think we need to call `dtoh` memcpy at all in `fillFab` because we don't need to initialize the `levelset` fab before calling `fillFab_Cpu`.

2022-01-11 01:11 UTC, WeiqunZhang approved these changes

2022-01-11 01:11 UTC, merged