Allow `FillBoundary` to cast messages from double to single precision.
AMReX-Codes/amrex pull request #2708
Opened 2022-04-11 22:18 UTC by hengjiew

## Summary
For the GPU implementation, this PR allows `FillBoundary` to pack double-precision data into a single-precision buffer and unpack single-precision messages to double-precision FabArray, e.x. `mf.template FillBoundary<float>(...)`. 

## Additional background

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2022-04-12 17:32 UTC, WeiqunZhang requested changes
LGTM.  I suggest we make the second typename required in `CellStore`, `CellAdd`, `CellAtomicAdd`, `fab_to_fab`, fab_to_fab_atomic_cpy`, and `fab_to_fab_atomic_add`.  These are not public, so we don't have to worry about API changes.  Also could we do this for CPU too?  We may need to modify functions like `BaseFab::copyFromMem` by adding an extra optional template parameter.

2022-04-12 17:32 UTC, WeiqunZhang commented on Src/Base/AMReX_FBI.H
> +             class U1=T1, std::enable_if_t<amrex::HasAtomicAdd<U1>::value,int> = 0>
We don't need to test if `T1` has atomic add because the value of `T1` will be cast to `T0`.

2022-04-15 22:36 UTC, hengjiew commented on Src/Base/AMReX_FBI.H
> +             class U1=T1, std::enable_if_t<amrex::HasAtomicAdd<U1>::value,int> = 0>
> LGTM. I suggest we make the second typename required in `CellStore`, `CellAdd`, `CellAtomicAdd`, `fab_to_fab`, fab_to_fab_atomic_cpy`, and `fab_to_fab_atomic_add`. These are not public, so we don't have to worry about API changes. Also could we do this for CPU too? We may need to modify functions like `BaseFab::copyFromMem` by adding an extra optional template parameter.

`BaseFab::copyFromMem` returns the size of the copied data. For casting and copying from a float buffer to a double fab, which return value makes more sense, sizeof(float)*N or sizeof(double)*N?

2022-04-15 22:37 UTC, hengjiew commented
> LGTM. I suggest we make the second typename required in `CellStore`, `CellAdd`, `CellAtomicAdd`, `fab_to_fab`, fab_to_fab_atomic_cpy`, and `fab_to_fab_atomic_add`. These are not public, so we don't have to worry about API changes. Also could we do this for CPU too? We may need to modify functions like `BaseFab::copyFromMem` by adding an extra optional template parameter.

`BaseFab::copyFromMem` returns the size of the copied data. For casting and copying from a float buffer to a double fab, which return value makes more sense, sizeof(float)*N or sizeof(double)*N?

2022-04-15 23:20 UTC, WeiqunZhang commented
The size in the 1d buffer, because the reason for returning the size is for the caller to increment the pointer to the buffer.

2022-04-18 18:36 UTC, WeiqunZhang approved these changes

2022-04-18 18:37 UTC, merged