Profiler Sync Timers
AMReX-Codes/amrex pull request #2784
Opened 2022-05-19 04:46 UTC by kngott

## Summary

Attempt 2. Tested on dogora in all configurations (no profiler, BL & Tiny).

Not the best methodology (adds a BL || Tiny macro test), but seems to do the job.

Will test on Perlmutter as well.

## Additional background

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2022-05-19 15:04 UTC, jmsexton03 commented on Src/Base/AMReX_BLProfiler.H
> +#define BL_TINY_PROFILE_INITIALIZE()   amrex::TinyProfiler::Initialize(); BLProfileSync::InitParams()
```suggestion
#define BL_TINY_PROFILE_INITIALIZE()   amrex::TinyProfiler::Initialize(); amrex::BLProfileSync::InitParams()
```

2022-05-19 16:22 UTC, WeiqunZhang requested changes
Don't you need to modify CMakeLists.txt?
```
diff --git a/Src/Base/CMakeLists.txt b/Src/Base/CMakeLists.txt
index ab86c6dfcc..935be24c8e 100644
--- a/Src/Base/CMakeLists.txt
+++ b/Src/Base/CMakeLists.txt
@@ -260,7 +260,7 @@ target_sources( amrex
 # Profiling
 #   this source file has zero symbols in default conditions, which creates
 #   ranlib warnings, e.g., on macOS
-if(AMReX_BASE_PROFILE OR AMReX_FORTRAN)
+if(AMReX_BASE_PROFILE OR OR AMReX_TINY_PROFILE OR AMReX_FORTRAN)
    target_sources( amrex
      PRIVATE
        AMReX_BLProfiler.cpp
```

2022-05-19 16:22 UTC, WeiqunZhang commented on Src/Base/AMReX_FabArrayCommI.H
> +    if (!fbd) { n_filled = IntVect::TheZeroVector(); BL_PROFILE_SYNC_STOP(); return; }
The only thing `BL_PROFILE_SYNC_STOP()` does is to decrement the counter.  So I think we could simply do it before this line and remove the one at the end of this function.

2022-05-19 16:41 UTC, kngott commented
Yup. Sure do! Was going to test it with WarpX on Perlmutter when I some cycles today, to track down and test the needed changes and get some fun numbers out at the same time. (PM was down last night). Looks like you may have found it, though. 😄

2022-05-19 16:43 UTC, kngott commented on Src/Base/AMReX_FabArrayCommI.H
> +    if (!fbd) { n_filled = IntVect::TheZeroVector(); BL_PROFILE_SYNC_STOP(); return; }
Ah, good point! I'll make that tweak.

2022-05-20 15:53 UTC, kngott commented
Tested all combinations on Perlmutter. They all work.

2022-05-26 17:31 UTC, WeiqunZhang approved these changes

2022-05-26 17:32 UTC, merged