make PODVector work with PolymorphicArenaAllocator
AMReX-Codes/amrex pull request #2829
Opened 2022-06-11 01:29 UTC by atmyers

This is a follow-on to PR #2705.

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2022-06-11 18:59 UTC, atmyers commented
@jmusser304 reported on Slack that this fixed the MFIX regression tests (where we first learned about this issue).

2022-06-13 17:06 UTC, WeiqunZhang requested changes

2022-06-13 17:06 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAllocators.H
> +    struct IsPolymorphic : std::false_type {};
Could we call it something more explicit like `IsPolymorphicArenaAllocator`?  The name `amrex::IsPolymorphic` might be misleading.

2022-06-13 20:56 UTC, WeiqunZhang approved these changes

2022-06-13 20:57 UTC, merged