SYCL: Replace deprecated atomic types and operations
AMReX-Codes/amrex pull request #2921
Opened 2022-08-19 18:02 UTC by nmnobre

## Summary

The atomic types and its operations provided by SYCL 1.2.1 used in AMReX are deprecated in SYCL 2020.
By replacing these, AMReX will, as far as I'm aware, be fully compliant with SYCL 2020.

Can the reviewer(s) please confirm we should be using `memory_scope::work_group` and not `memory_scope::sub_group`?

Cheers,
Nuno

2022-08-22 16:08 UTC, WeiqunZhang commented
Because we are using the relaxed ordering, which imposes no orders on concurrent memory accesses, maybe `memory_scope::work_item` is all we need.  I want to do some testing and think more about this.

2022-08-23 15:43 UTC, nmnobre commented
Take your time @WeiqunZhang :-)

What you said made me go read a bit more of the spec and, indeed, the section on [Memory Scope](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_memory_scope) clearly says the passed memory scope determines "the memory ordering constraints of a given atomic operation".

I was under the (wrong?) impression that it (also) determined the atomicity scope, i.e. the encompassing range of the mutex if you will... Since we are dealing with global memory, my thinking was that, in general, we'd need to guarantee atomicity across the whole device.

In DPC++, they use `spirv::AtomicIAdd` underneath, for which I found [this](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpAtomicIAdd) which adds "atomically with respect to any other atomic accesses within Scope to the same location"...
I'm a bit confused.

Thank you for your time,
-Nuno

2022-08-26 18:54 UTC, WeiqunZhang commented
@nmnobre We have reached out to Intel for help.  @bashbaug has confirmed that in the Intel implementation the memory scope is ignored for the relaxed memory order.  Here is a link to how atomics are handled in the Intel graphics compiler. https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Implementation/atomics.cl. Because the relaxed memory order is not in PRE_OP_NEED_FENCE and POST_OP_NEEDS_FENCE,  scope checks and fence handling are skipped.

So I think we can change it to either `memory_scope::device` or `memory_scope::work_item` even though it does not matter.

2022-09-01 14:57 UTC, WeiqunZhang requested changes

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-01 14:57 UTC, WeiqunZhang commented on Src/Base/AMReX_GpuAtomic.H
> +        constexpr auto ms = sycl::memory_scope::work_group;
```suggestion
        constexpr auto ms = sycl::memory_scope::device;
```

2022-09-04 04:18 UTC, WeiqunZhang approved these changes

2022-09-04 04:18 UTC, merged