Fix: Finalize Arena to nullptrs
AMReX-Codes/amrex pull request #2944
Opened 2022-09-09 23:17 UTC by ax3l

## Summary

The arenas are not set in all cases to `nullptr`s yet. This causes that repeated finalize/initialize calls fail.

## Additional background

Seen in https://github.com/ECP-WarpX/impactx/pull/172

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2022-09-10 00:00 UTC, WeiqunZhang commented
The fix might be wrong.  I think it could lead to memory leak when BArena is used (which is the default for CPU builds).  Maybe we should fix the assertions instead.  Change it to `BL_ASSERT(the_arena==nullptr || the_arena == The_BArena())`.

The reason we want `the_arena` to be still valid in case of BArena after Arena::Finalize is called is the user's codes often have memory allocate by The_Arena still around after amrex::Finalize is called.  One could argue it's the user's fault.  But we have got questions about this kind of error so many times, it's really our fault to make it easy to make mistakes.  So we decided to keep the Arena alive so that the memory can still be freed.

2022-09-10 00:08 UTC, WeiqunZhang commented
Here is an example of the kind of error often reported to us.
```
amrex::Initialize(...)
MultiFab mf(...);
amrex::Finalize();
```
The dtor `~MultiFab` is called after `amrex::Finalize()`.  It could be fixed by limiting the scope of `mf`.  But it was so common that we decided to make it work without worrying about the scope.

2022-09-10 00:15 UTC, WeiqunZhang commented
Or we can just remove the assertion.  Also maybe you can add my comment to Arena::Finalize to explain why the pointers are not reset if it's a BArena.

2022-09-10 00:20 UTC, ax3l commented
The problem right now is that you cannot call `Initialize()` after `Finalize()` without triggering the assert.

Yes, that MF should be scoped. I also cannot all `MPI_Barrier` after `MPI_Finalize()`, it's an API contract and will leave some things dangling either way.

2022-09-10 00:23 UTC, ax3l commented
Note that I will run various runs of AMReX in the same process sequentially, finalizing in between.
I need a really clean slay after `Finalize()` or will debug myself int oblivion about half-resetted globals of AMReX.

2022-09-10 00:48 UTC, ax3l commented
Looking at `Arena::Initialize`, I think if we use `BL_ASSERT(the_arena==nullptr || the_arena == The_BArena())` then we will craete a memory leak between subsequent `Finalize()` and `Initialize()` calls.

2022-09-10 00:51 UTC, WeiqunZhang commented
Can you explain why they would be a memory leak?

2022-09-10 00:52 UTC, ax3l commented
I think because we would loose the handle to the existing arena and assign a fresh one here:
https://github.com/AMReX-Codes/amrex/blob/67384701a808ca973ad2c24ec86cee4c7a81fd05/Src/Base/AMReX_Arena.cpp#L314

2022-09-10 00:53 UTC, ax3l commented
> The dtor ~MultiFab is called after amrex::Finalize(). It could be fixed by limiting the scope of mf. But it was so common that we decided to make it work without worrying about the scope.

Can we throw a warning in `amrex::Finalize()`/`~Arena` if there is still allocated memory in them? That would mean people did not scope their AMReX allocs when they reach that point, no?

2022-09-10 00:55 UTC, WeiqunZhang commented
But the BArena is a static object in the The_BArena() function.  So it's the same handler.

2022-09-10 01:00 UTC, ax3l commented
True, that works.

For the original problem:
> The dtor ~MultiFab is called after amrex::Finalize(). It could be fixed by limiting the scope of mf. But it was so common that we decided to make it work without worrying about the scope.

Can we throw a warning in `amrex::Finalize()`/`~Arena` if there is still allocated memory in them? That would mean people did not scope their AMReX allocs when they reach that point, no?
That would also give them hints that they have dangling / UB variables still around.

2022-09-12 02:41 UTC, WeiqunZhang requested changes

2022-09-12 02:41 UTC, WeiqunZhang commented on Src/Base/AMReX_Arena.cpp
> +    BL_ASSERT(the_device_arena == nullptr || the_arena == The_BArena());
```suggestion
    BL_ASSERT(the_device_arena == nullptr || the_device_arena == The_BArena());
```

2022-09-12 02:41 UTC, WeiqunZhang commented on Src/Base/AMReX_Arena.cpp
> +    BL_ASSERT(the_managed_arena == nullptr || the_arena == The_BArena());
```suggestion
    BL_ASSERT(the_managed_arena == nullptr || the_managed_arena == The_BArena());
```

2022-09-12 02:41 UTC, WeiqunZhang commented on Src/Base/AMReX_Arena.cpp
> +    BL_ASSERT(the_cpu_arena == nullptr || the_arena == The_BArena());
```suggestion
    BL_ASSERT(the_cpu_arena == nullptr || the_cpu_arena == The_BArena());
```

2022-09-12 18:39 UTC, WeiqunZhang approved these changes

2022-09-12 18:40 UTC, merged