[WIP] Profile memory allocations of the CArena using TinyProfiler
AMReX-Codes/amrex pull request #3105
Opened 2023-01-22 17:05 UTC by AlexanderSinn

## Summary

## Additional background

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2023-01-24 18:08 UTC, WeiqunZhang requested changes

2023-01-24 18:08 UTC, WeiqunZhang commented on Src/Base/AMReX_CArena.cpp
> +struct MemStat {};
Could we add `namespace amrex` here?

2023-01-24 18:08 UTC, WeiqunZhang commented on Src/Base/AMReX_TinyProfiler.H
> +#pragma omp threadprivate(mem_stack_thread_private)
It appears that some compilers do not work well with omp threadprivate.  In `AMReX_BLBackTrace.H`, we have to do something like this.
```
struct BLBackTrace
{   
    ...
    static std::stack<std::pair<std::string, std::string> > bt_stack;
// threadprivate here doesn't work with Cray, Intel, and Fujitsu                                                                                                             
#if defined(AMREX_USE_OMP) && !defined(_CRAYC) && !defined(__INTEL_COMPILER) && !defined(__PGI) && !defined(__NVCOMPILER) && !defined(__FUJITSU)
#pragma omp threadprivate(bt_stack)
#endif
};
```
This is a hack just to get the code to compile.  We should fix it in a better way.

For the threadprivate variable here, we could make it a vector and resize it to the number of max threads.  Then each thread can have its private variable.  We can do the resize in TinyProfiler::Initiallize that is already called by amrex::Initialize.

2023-01-24 19:30 UTC, AlexanderSinn commented on Src/Base/AMReX_CArena.cpp
> +struct MemStat {};
Yes

2023-01-24 19:45 UTC, AlexanderSinn commented on Src/Base/AMReX_TinyProfiler.H
> +#pragma omp threadprivate(mem_stack_thread_private)
I added this. That approach is prone to false sharing, so I made sure the distance between thread private objects is large enough.

2023-01-24 19:53 UTC, WeiqunZhang commented on Src/Base/AMReX_TinyProfiler.H
> +#pragma omp threadprivate(mem_stack_thread_private)
You can have vector or unique_ptr of the objects.  That probably will be fine.

2023-02-06 16:02 UTC, WeiqunZhang commented
I find the concept of AvgMem confusing.  For example, how should we think about `43 KiB`?
```
---------------------------------------------------------------------------
Name                                      Nalloc  Nfree    AvgMem    MaxMem
---------------------------------------------------------------------------
The_Arena::Initialize()                        1      1    43 KiB    29 GiB
```

2023-02-06 17:19 UTC, AlexanderSinn commented
```
---------------------------------------------------------------------------
Name                                      Nalloc  Nfree    AvgMem    MaxMem
---------------------------------------------------------------------------
The_Arena::Initialize()                        1      1    43 KiB    29 GiB
```
Here AvgMem is significantly less than MaxMem. Functions like this require memory when they execute, but give it back to the system shortly after. In this case it is deallocated immediately. If the memory footprint of such a function where to be reduced, it may help the application as a whole very little unless it would run out of memory in this function.
```
---------------------------------------------------------------------------
Name                                      Nalloc  Nfree    AvgMem    MaxMem
---------------------------------------------------------------------------
Fields::AllocData()                            3      3  2820 MiB  2820 MiB
```
Here AvgMem is the same as MexMem. This function allocates a chunk of memory at the start and keeps it for the lifetime of the program. Reducing the amount of memory used in this function would allow the entire rest of the program to use more memory.
```
---------------------------------------------------------------------------
Name                                      Nalloc  Nfree    AvgMem    MaxMem
---------------------------------------------------------------------------
PlasmaParticleContainer::InitParticles        34     34  4554 MiB  4737 MiB
```
Here AvgMem is a little less than MaxMem. In this case it is caused by allocating a chunk of memory and keeping it until the program ends, however additional memory is required for initialization that if freed early. It may make more sense to try to reduce AvgMem rather than MaxMem, unless MaxMem is too large.

2023-02-07 18:49 UTC, WeiqunZhang approved these changes

2023-02-07 18:50 UTC, merged