New feature in EB: Add regular coarse levels
AMReX-Codes/amrex pull request #3414
Opened 2023-07-09 19:46 UTC by WeiqunZhang

## Summary

This feature could be useful when the EB is so thin that it is only resolved at the finest level and the usual way of generate coarse levels fails with multi-cut or multi-value cells. When the EB is fully refined to the finest level and there is no subcycling, no EB information is really needed at coarse levels. Note that tagging cut cells for refinement no longer works if that level has all regular EB.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2023-07-10 14:19 UTC, drummerdoc requested changes
I think this means that we need to implement some other approach to keep the fine grid on the EB or we'll lose it on the first regrid.  Is there somewhere the capability to tag IntVects on the coarse level where there are cut cells on the fine?

2023-07-10 19:03 UTC, WeiqunZhang commented
Are you using `amrex::TagCutCells`? We can probably make it work for this case.

2023-07-10 20:16 UTC, drummerdoc commented
> Are you using `amrex::TagCutCells`? We can probably make it work for this case.

Yeah, using that.

2023-07-11 16:48 UTC, WeiqunZhang commented
amrex::TagCutCell has been updated. I tested with EB_CNS. Regrid appears to work.
```
diff --git a/Tests/EB_CNS/Source/CNS_init_eb2.cpp b/Tests/EB_CNS/Source/CNS_init_eb2.cpp
index c64663a8bb..a729aebedf 100644
--- a/Tests/EB_CNS/Source/CNS_init_eb2.cpp
+++ b/Tests/EB_CNS/Source/CNS_init_eb2.cpp
@@ -69,6 +69,8 @@ initialize_EB2 (const Geometry& geom, int /*required_coarsening_level*/,
     else
 #endif
     {
-        EB2::Build(geom, max_coarsening_level, max_coarsening_level, 4);
+//        EB2::Build(geom, max_coarsening_level, max_coarsening_level, 4);
+        EB2::Build(geom, 0, 0, 4);
+        EB2::addRegularCoarseLevels(max_coarsening_level);
     }
 }
```

2023-07-11 16:57 UTC, drummerdoc approved these changes
Excellent!  Thanks Weiqun.  This looks great.  Can't wait to try it out on a thin body problem!

2023-07-11 17:05 UTC, WeiqunZhang commented
Hopefully, the fully covered cells will not cause any issues for your code.

2023-07-11 17:16 UTC, drummerdoc commented
> Hopefully, the fully covered cells will not cause any issues for your code.

What's the concern?

2023-07-11 17:28 UTC, WeiqunZhang commented
Like averageDown triggers floating point exceptions.

2023-07-12 00:12 UTC, merged