Adding bittree interface to improve regridding performance in octree mode
AMReX-Codes/amrex pull request #3555
Opened 2023-09-18 18:18 UTC by akashdhruv

## Summary

This PR introduces dependency on [Bittree library](https://github.com/Flash-X/Bittree) to improve regridding performance in octree mode.

## Additional background

Testing and development of this feature is done in sync with Flash-X and is recorded in this [reproducibility capsule](https://github.com/Lab-Notebooks/AMReX-Bittree-Performance). This PR is primarily created to consolidate development work and avoid creating multiple branches. At present using AMReX+Bittree improves regridding performance [by a factor of 2](https://github.com/Lab-Notebooks/AMReX-Bittree-Performance/blob/14faa2212c4e5dba7fd99a6526c6937414f9c109/analysis/Performance.ipynb) at > 20000 ranks. We hope to improve performance further using a bittree-based distribution mapping and therefore adding a new function `AmrMesh::MakeDistributionMap` as a place-holder.

Continuation of #2893 and #3547

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

2023-09-28 21:43 UTC, WeiqunZhang requested changes
I will add a CI after this a merged.

2023-09-28 21:43 UTC, WeiqunZhang commented on Src/AmrCore/AMReX_AmrMesh.H
> +    bool use_bittree;
```suggestion
    bool use_bittree = false;
```
We can have a default value. Then `use_bittree` will not longer be a required parameter.

2023-09-28 21:43 UTC, WeiqunZhang commented on Src/AmrCore/AMReX_AmrMesh.H
> +    std::shared_ptr<bittree::BittreeAmr> btmesh;
```suggestion
    std::unique_ptr<bittree::BittreeAmr> btmesh;
```
We could use unique_ptr instead.

2023-09-28 21:43 UTC, WeiqunZhang commented on Src/AmrCore/AMReX_AmrMesh.cpp
> +            btmesh = std::make_shared<bittree::BittreeAmr>(top.data(),includes.data());
```suggestion
            btmesh = std::make_unique<bittree::BittreeAmr>(top.data(),includes.data());
```

2023-09-28 21:43 UTC, WeiqunZhang commented on Src/AmrCore/AMReX_AmrMesh.cpp
> +    pp.get("use_bittree",use_bittree);
```suggestion
    pp.queryAdd("use_bittree",use_bittree);
```

2023-09-28 21:43 UTC, WeiqunZhang commented on Src/AmrCore/AMReX_AmrMesh.cpp
> +    amrex::Print() << "creating new distribution map on level: " << lev + 1 << "\n";
```suggestion
    if (verbose) {
        amrex::Print() << "Creating new distribution map on level: " << lev << "\n";
    }
```
Don't want to print this if verbose is 0. Also let's use the C++ convention that level numbering starts with 0.

2023-09-28 21:43 UTC, WeiqunZhang commented on Src/AmrCore/AMReX_AmrMesh.cpp
> +    return dm;
```suggestion
#ifdef AMREX_USE_BITTREE
    // if (use_bittree) {
    //     return DistributionMapping(ba);
    // } else
#endif
    {
        return DistributionMapping(ba);
    }
```

2023-09-28 21:53 UTC, WeiqunZhang commented
I have run the test at `amrex/Tests/Amr/Advection_AmrCore/Exec`. It works as expected. However, the grids generated are not very efficient.

![phi_plt00080_bittree](https://github.com/AMReX-Codes/amrex/assets/7862753/8d6b4537-fd14-4af2-a710-f805db4aac06)
This is a picture from a run using bittree.

![phi_plt00080_native](https://github.com/AMReX-Codes/amrex/assets/7862753/fffe2900-6bbd-47bd-81a1-82058ce5204f)
This is from a run using the native *non-tree* mode. The area covered by level 1 grids is much smaller.

2023-09-28 22:07 UTC, akashdhruv commented
> I have run the test at `amrex/Tests/Amr/Advection_AmrCore/Exec`. It works as expected. However, the grids generated are not very efficient.
> 
> ![phi_plt00080_bittree](https://user-images.githubusercontent.com/7862753/271425313-8d6b4537-fd14-4af2-a710-f805db4aac06.png) This is a picture from a run using bittree.
> 
> ![phi_plt00080_native](https://user-images.githubusercontent.com/7862753/271425735-fffe2900-6bbd-47bd-81a1-82058ce5204f.png) This is from a run using the native _non-tree_ mode. The area covered by level 1 grids is much smaller.

I think the refine-derefine criteria maybe too strict. I can look into this after the merge, and create a follow-up PR

2023-09-28 22:15 UTC, WeiqunZhang commented on Src/Extern/Bittree/AMReX_Bittree.cpp
> +/** Calculate integer coordinates of neighbors, taking into acount BCs.
```suggestion
/** Calculate integer coordinates of neighbors, taking into account BCs.
```

2023-09-29 02:00 UTC, kweide commented
> the grids generated are not very efficient.

I think we cannot do much better, given the octtree-mimicking parameters that we are using (and have been using way before Bittree) in Flash-X for the AMR/Amrex Grid implementation:
```Fortran
  ! Setup AMReX in octree mode
  call pp_amr%add   ("max_grid_size_x",     NXB)
  call pp_amr%add   ("max_grid_size_y",     NYB)
  call pp_amr%add   ("max_grid_size_z",     NZB)
  call pp_amr%add   ("blocking_factor_x", 2*NXB)
  call pp_amr%add   ("blocking_factor_y", 2*NYB)
  call pp_amr%add   ("blocking_factor_z", 2*NZB)
  call pp_amr%add   ("refine_grid_layout", 0)
  call pp_amr%add   ("grid_eff",  1.0)

  ! According to Weiqun n_proper=1 is an appropriate setting that will result in
  ! correct nesting.
  call pp_amr%add("n_proper", 1)
```
This is from our `gr_amrexInit.F90`. Maybe not all the lines are relevant here, maybe only the first 6 are. 

(I think at one point at least I understood how the `max_grid_size_` and `blocking_factor_` AMReX parameters work, and why they have to be set this way in order to limit refinement patters to the octtree-ish ones that can be generated by PARAMESH.)

2023-10-01 18:33 UTC, WeiqunZhang approved these changes

2023-10-01 18:34 UTC, merged

2024-01-04 19:39 UTC, akashdhruv commented
> ![phi_plt00080_bittree](https://private-user-images.githubusercontent.com/7862753/271425313-8d6b4537-fd14-4af2-a710-f805db4aac06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTczODYsIm5iZiI6MTcwNDM5NzA4NiwicGF0aCI6Ii83ODYyNzUzLzI3MTQyNTMxMy04ZDZiNDUzNy1mZDE0LTRhZjItYTcxMC1mODA1ZGI0YWFjMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTkzODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRmNzViZjA0MzIzZjI2MDA5Njg5YmQyOWYyY2U3YjgwOTU1YmJiOWFmNDdjNGViNzFlMDFhODM5ZGM2MTcxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sw4vzTuODVVC9XZpj8RaDHaXjajE54tKilTmNuRpeE8) This is a picture from a run using bittree.
> 

@WeiqunZhang Can you create a time evolution so we can see how derefinement logic is working?